server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/social_platform
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkey
  expiration: 86400000 # 24 hours

management:
  endpoints:
    web:
      exposure:
        include: "health,info"  # 只公开必要的端点
  endpoint:
    health:
      show-details: always

