apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
    isDefault: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "[logs-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      timeField: "@timestamp"
      esVersion: 8.0.0
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level