global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 规则加载和配置
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api_gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["nginx:80"]

  - job_name: "user_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:8000"]

  - job_name: "post_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["post-service:8000"]

  - job_name: "notification_service"
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-service:8000"]

  - job_name: "elasticsearch"
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets: ["elasticsearch:9200"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9308"]